- name: set selinux disable
  selinux: state=disabled
- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - mariadb-server
    - MySQL-python
- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
- name: enable mariadb
  service: name=mariadb state=restarted enabled=yes
- name: create database
  mysql_db: name=wordpress state=present
- name: grant database
  mysql_user: name=wordpress password="wordpress" host=% priv=wordpress.*:ALL

