- include_vars: group_vars/db
- name: install MySQL-python
  yum: name=MySQL-python state=latest
- name: create database
  mysql_db: name={{ wordpress.db_name }} state=present
- name: grant database
  mysql_user: name={{ wordpress.db_user }} password={{ wordpress.db_password }} host=% priv={{ wordpress.db_name }}.*:ALL

