- name: install httpd
  yum: name=httpd state=latest
  notify: restart httpd
- name: configure apache settings
  replace: dest=/etc/httpd/conf/httpd.conf regexp='{{ item.regexp }}' replace='{{ item.replace }}'
  with_items:
  - regexp: '"/var/www/html"'
    replace: '"/var/www/html/wordpress"'
  - regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
  notify: restart httpd
