- name: check selinux
  command: getenforce
  register: selinux_result
  changed_when: false
  always_run: yes
- name: set selinux disable
  selinux: state=disabled
  when: selinux_result.stdout.find("Enforcing") != -1
- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
